export const FETCH_CATEGORIES_STARTS = 'FETCH_CATEGORIES_STARTS';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS ';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED ';

export const ADD_CATEGORY_START = 'ADD_CATEGORY_START';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS ';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED ';


export const FETCH_PRODUCTS_STARTS = 'FETCH_PRODUCTS_STARTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS ';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED ';

export const FETCH_CARTITEMS_STARTS = 'FETCH_CARTITEMS_STARTS';
export const FETCH_CARTITEMS_SUCCESS = 'FETCH_CARTITEMS_SUCCESS';
export const FETCH_CARTITEMS_FAILED  = 'FETCH_CARTITEMS_FAILED';

export const DELETE_CARTITEM_STARTS = 'DELETE_CARTITEMS_STARTS';
export const DELETE_CARTITEM__SUCCESS = 'DELETE_CARTITEMS__SUCCESS';
export const DELETE_CARTITEM_FAILED  = 'DELETE_CARTITEMS_FAILED';

export const ADD_CARTITEM_STARTS = 'ADD_CARTITEM_STARTS';
export const ADD_CARTITEM_SUCCESS = 'ADD_CARTITEM_SUCCESS';
export const ADD_CARTITEM_FAILED  = 'ADD_CARTITEM_FAILED';

export const REDUCE_CARTITEM_STARTS = 'REDUCE_CARTITEM_STARTS';
export const REDUCE_CARTITEM_SUCCESS = 'REDUCE_CARTITEM_SUCCESS';
export const REDUCE_CARTITEMS_FAILED  = 'REDUCE_CARTITEM_FAILED';

export const CLEAR_CART_ITEMS  = 'CLEAR_CART_ITEMS';



export const FETCH_LIKED_STARTS = 'FETCH_LIKED_STARTS';
export const FETCH_LIKED_SUCCESS = 'FETCH_LIKED_SUCCESS';
export const FETCH_LIKED_FAILED  = 'FETCH_LIKED_FAILED';

export const FETCH_HOMEDATA_STARTS = 'FETCH_HOMEDATA_STARTS';
export const FETCH_HOMEDATA_SUCCESS = 'FETCH_HOMEDATA_SUCCESS';
export const FETCH_HOMEDATA_FAILED  = 'FETCH_HOMEDATA_FAILED';


export const ADD_LIKED_STARTS = 'ADD_LIKED_STARTS';
export const ADD_LIKED_SUCCESS = 'ADD_LIKED_SUCCESS';
export const ADD_LIKED_FAILED  = 'ADD_LIKED_FAILED';

export const CLEAR_LIKED_ITEMS  = 'CLEAR_LIKED_ITEMS';


export const AUTH_START = 'AUTH_START'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const LOGOUT = 'LOGOUT'


export const SET_PERSON_INFORMATION = 'SET_PERSON_INFORMATION'
export const SET_ORDER_PLACE = 'SET_ORDER_PLACE'
export const SET_DELEVERY_COST = 'SET_DELEVERY_COST'


export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'


